Tue, 07 Jan 2020 09:25:17 - INFO - Connect to DB
Tue, 07 Jan 2020 09:25:17 - INFO - TRIZMA DB import
Tue, 07 Jan 2020 09:25:17 - INFO - 123TV DB import
Tue, 07 Jan 2020 09:25:23 - INFO - Connect to DB
Tue, 07 Jan 2020 09:25:23 - INFO - TRIZMA DB import
Tue, 07 Jan 2020 09:25:23 - INFO - 123TV DB import
Tue, 07 Jan 2020 09:26:16 - INFO - Connect to DB
Tue, 07 Jan 2020 09:26:16 - INFO - TRIZMA DB import
Tue, 07 Jan 2020 09:26:16 - INFO - 123TV DB import
Tue, 07 Jan 2020 09:26:24 - INFO - Connect to DB
Tue, 07 Jan 2020 09:26:24 - INFO - TRIZMA DB import
Tue, 07 Jan 2020 09:26:24 - INFO - 123TV DB import
Tue, 07 Jan 2020 09:27:10 - INFO - Connect to DB
Tue, 07 Jan 2020 09:27:10 - INFO - TRIZMA DB import
Tue, 07 Jan 2020 09:27:10 - INFO - 123TV DB import
Tue, 07 Jan 2020 09:27:51 - INFO - Connect to DB
Tue, 07 Jan 2020 09:27:51 - INFO - TRIZMA DB import
Tue, 07 Jan 2020 09:27:51 - INFO - 123TV DB import
Tue, 07 Jan 2020 09:29:01 - INFO - Connect to DB
Tue, 07 Jan 2020 09:29:01 - INFO - TRIZMA DB import
Tue, 07 Jan 2020 09:29:02 - INFO - Failed on TRIZMA DB import at: 2020-01-07_09-24-45, for following calling party: 4952018769860, for agent id: trz_sstankovic, with error:(pyodbc.DataError) ('22001', '[22001] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]String or binary data would be truncated. (8152) (SQLExecDirectW)')
[SQL: insert into records values('CC2Servicenummer','Belgrad','Nicht übermittelt','trz_sstankovic',                                  '4952018769860','','Nicht übermittelt','4952018769860_Tuesday, January 07, 2020_10:28:59 AM')]
(Background on this error at: http://sqlalche.me/e/9h9h)
Tue, 07 Jan 2020 09:29:02 - INFO - 123TV DB import
