Mon, 06 Jan 2020 07:19:41 - INFO - Connect to DB
Mon, 06 Jan 2020 07:19:42 - ERROR - Exception on /records [GET]
Traceback (most recent call last):
  File "/home/python_project/hello.py", line 80, in get
    int(agent),
ValueError: invalid literal for int() with base 10: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/python_project/hello.py", line 90, in get
    + str(e))
UnboundLocalError: local variable 'agentUsername' referenced before assignment
Mon, 06 Jan 2020 07:21:03 - INFO - Connect to DB
Mon, 06 Jan 2020 07:21:03 - INFO - TRIZMA DB import
Mon, 06 Jan 2020 07:21:03 - INFO - 123TV DB import
Mon, 06 Jan 2020 07:21:50 - INFO - Connect to DB
Mon, 06 Jan 2020 07:21:50 - INFO - TRIZMA DB import
Mon, 06 Jan 2020 07:21:50 - INFO - 123TV DB import
Mon, 06 Jan 2020 07:21:55 - INFO - Connect to DB
Mon, 06 Jan 2020 07:21:55 - INFO - TRIZMA DB import
Mon, 06 Jan 2020 07:21:56 - INFO - 123TV DB import
Mon, 06 Jan 2020 07:22:30 - INFO - Connect to DB
Mon, 06 Jan 2020 07:22:30 - INFO - TRIZMA DB import
Mon, 06 Jan 2020 07:22:30 - INFO - 123TV DB import
Mon, 06 Jan 2020 07:23:15 - INFO - Connect to DB
Mon, 06 Jan 2020 07:23:15 - INFO - TRIZMA DB import
Mon, 06 Jan 2020 07:23:15 - INFO - 123TV DB import
Mon, 06 Jan 2020 07:29:26 - INFO - Connect to DB
Mon, 06 Jan 2020 07:29:26 - INFO - TRIZMA DB import
Mon, 06 Jan 2020 07:29:26 - INFO - 123TV DB import
Mon, 06 Jan 2020 07:29:59 - INFO - Connect to DB
Mon, 06 Jan 2020 07:29:59 - INFO - TRIZMA DB import
Mon, 06 Jan 2020 07:29:59 - INFO - 123TV DB import
Mon, 06 Jan 2020 07:30:07 - INFO - Connect to DB
Mon, 06 Jan 2020 07:30:07 - INFO - TRIZMA DB import
Mon, 06 Jan 2020 07:30:07 - INFO - Failed on TRIZMA DB import at: 2020-01-06_07-14-36, for following calling party: 4934522602628, for agent id: trz_sstankovic, with error:(pyodbc.DataError) ('22001', '[22001] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]String or binary data would be truncated. (8152) (SQLExecDirectW)')
[SQL: insert into records values('CC2Servicenummer','Belgrad','Nicht übermittelt','trz_sstankovic',                                  '4934522602628','','Nicht übermittelt','4934522602628_Tuesday, December 31, 2019_11:24:24 AM')]
(Background on this error at: http://sqlalche.me/e/9h9h)
Mon, 06 Jan 2020 07:30:07 - INFO - 123TV DB import
Mon, 06 Jan 2020 07:30:22 - INFO - Connect to DB
Mon, 06 Jan 2020 07:30:22 - INFO - TRIZMA DB import
Mon, 06 Jan 2020 07:30:22 - INFO - Failed on TRIZMA DB import at: 2020-01-06_07-14-36, for following calling party: 491731864217, for agent id: trz_sstankovic, with error:(pyodbc.DataError) ('22001', '[22001] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]String or binary data would be truncated. (8152) (SQLExecDirectW)')
[SQL: insert into records values('CC2Servicenummer','Belgrad','Nicht übermittelt','trz_sstankovic',                                  '491731864217','','Nicht übermittelt','491731864217_Tuesday, December 31, 2019_12:52:51 PM')]
(Background on this error at: http://sqlalche.me/e/9h9h)
Mon, 06 Jan 2020 07:30:22 - INFO - 123TV DB import
Mon, 06 Jan 2020 07:30:29 - INFO - Connect to DB
Mon, 06 Jan 2020 07:30:29 - INFO - TRIZMA DB import
Mon, 06 Jan 2020 07:30:29 - INFO - 123TV DB import
Mon, 06 Jan 2020 07:32:28 - INFO - Connect to DB
Mon, 06 Jan 2020 07:32:28 - INFO - TRIZMA DB import
Mon, 06 Jan 2020 07:32:28 - INFO - Failed on TRIZMA DB import at: 2020-01-06_07-14-36, for following calling party: 4917655909929, for agent id: trz_sstankovic, with error:(pyodbc.DataError) ('22001', '[22001] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]String or binary data would be truncated. (8152) (SQLExecDirectW)')
[SQL: insert into records values('CC2Servicenummer','Belgrad','Nicht übermittelt','trz_sstankovic',                                  '4917655909929','','Nicht übermittelt','4917655909929_Tuesday, December 31, 2019_2:25:59 PM')]
(Background on this error at: http://sqlalche.me/e/9h9h)
Mon, 06 Jan 2020 07:32:28 - INFO - 123TV DB import
Mon, 06 Jan 2020 07:33:23 - INFO - Connect to DB
Mon, 06 Jan 2020 07:33:23 - INFO - TRIZMA DB import
Mon, 06 Jan 2020 07:33:23 - INFO - 123TV DB import
Mon, 06 Jan 2020 07:34:21 - INFO - Connect to DB
Mon, 06 Jan 2020 07:34:21 - INFO - TRIZMA DB import
Mon, 06 Jan 2020 07:34:21 - INFO - 123TV DB import
Mon, 06 Jan 2020 07:40:40 - INFO - Connect to DB
Mon, 06 Jan 2020 07:40:40 - INFO - TRIZMA DB import
Mon, 06 Jan 2020 07:40:40 - INFO - 123TV DB import
Mon, 06 Jan 2020 07:44:47 - INFO - Connect to DB
Mon, 06 Jan 2020 07:44:47 - INFO - TRIZMA DB import
Mon, 06 Jan 2020 07:44:48 - INFO - 123TV DB import
Mon, 06 Jan 2020 07:45:34 - INFO - Connect to DB
Mon, 06 Jan 2020 07:45:34 - INFO - TRIZMA DB import
Mon, 06 Jan 2020 07:45:34 - INFO - 123TV DB import
Mon, 06 Jan 2020 07:46:47 - INFO - Connect to DB
Mon, 06 Jan 2020 07:46:47 - INFO - TRIZMA DB import
Mon, 06 Jan 2020 07:46:47 - INFO - 123TV DB import
Mon, 06 Jan 2020 07:46:57 - INFO - Connect to DB
Mon, 06 Jan 2020 07:46:57 - INFO - TRIZMA DB import
Mon, 06 Jan 2020 07:46:57 - INFO - 123TV DB import
