Sat, 21 Dec 2019 09:00:09 - INFO - Connect to DB
Sat, 21 Dec 2019 09:00:09 - ERROR - Exception on /records [GET]
Traceback (most recent call last):
  File "/home/python_project/hello.py", line 80, in get
    int(agent),
ValueError: invalid literal for int() with base 10: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/python_project/hello.py", line 90, in get
    + str(e))
UnboundLocalError: local variable 'agentUsername' referenced before assignment
Sat, 21 Dec 2019 09:12:18 - INFO - Connect to DB
Sat, 21 Dec 2019 09:12:18 - INFO - TRIZMA DB import
Sat, 21 Dec 2019 09:12:18 - INFO - 123TV DB import
Sat, 21 Dec 2019 09:34:46 - INFO - Connect to DB
Sat, 21 Dec 2019 09:34:46 - INFO - TRIZMA DB import
Sat, 21 Dec 2019 09:34:46 - INFO - Failed on TRIZMA DB import at: 2019-12-21_08-30-28, for following calling party: 4922029262750, for agent id: trz_ppetkovic, with error:(pyodbc.DataError) ('22001', '[22001] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]String or binary data would be truncated. (8152) (SQLExecDirectW)')
[SQL: insert into records values('CC2Servicenummer','Belgrad','Nicht übermittelt','trz_ppetkovic',                                  '4922029262750','','Nicht übermittelt','4922029262750_Saturday, December 21, 2019_10:34:35 AM')]
(Background on this error at: http://sqlalche.me/e/9h9h)
Sat, 21 Dec 2019 09:34:46 - INFO - 123TV DB import
