Fri, 27 Dec 2019 15:55:11 - INFO - Connect to DB
Fri, 27 Dec 2019 15:55:12 - ERROR - Exception on /records [GET]
Traceback (most recent call last):
  File "/home/python_project/hello.py", line 81, in get
    1)).fetchone()[0]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/python_project/hello.py", line 90, in get
    + str(e))
UnboundLocalError: local variable 'agentUsername' referenced before assignment
Fri, 27 Dec 2019 16:03:00 - INFO - Connect to DB
Fri, 27 Dec 2019 16:03:00 - INFO - TRIZMA DB import
Fri, 27 Dec 2019 16:03:01 - INFO - 123TV DB import
Fri, 27 Dec 2019 16:12:37 - INFO - Connect to DB
Fri, 27 Dec 2019 16:12:37 - INFO - TRIZMA DB import
Fri, 27 Dec 2019 16:12:37 - INFO - 123TV DB import
Fri, 27 Dec 2019 16:19:11 - INFO - Connect to DB
Fri, 27 Dec 2019 16:19:11 - INFO - TRIZMA DB import
Fri, 27 Dec 2019 16:19:11 - INFO - 123TV DB import
