Wed, 08 Jan 2020 07:18:53 - INFO - Connect to DB
Wed, 08 Jan 2020 07:18:53 - INFO - TRIZMA DB import
Wed, 08 Jan 2020 07:18:53 - INFO - Failed on TRIZMA DB import at: 2020-01-08_07-04-04, for following calling party: 4921514465785, for agent id: trz_madamovic, with error:(pyodbc.DataError) ('22001', '[22001] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]String or binary data would be truncated. (8152) (SQLExecDirectW)')
[SQL: insert into records values('CC2Servicenummer','Belgrad','Nicht übermittelt','trz_madamovic',                                  '4921514465785','','Nicht übermittelt','4921514465785_Thursday, December 26, 2019_11:19:36 AM')]
(Background on this error at: http://sqlalche.me/e/9h9h)
Wed, 08 Jan 2020 07:18:53 - INFO - 123TV DB import
Wed, 08 Jan 2020 07:18:58 - INFO - Failed on 123TV DB import at: 2020-01-08_07-04-04, for following calling party: 4921514465785, for agent id: 3067, with error:Invalid XML content received (Start tag expected, '<' not found, line 1, column 1)
Wed, 08 Jan 2020 07:21:24 - INFO - Connect to DB
Wed, 08 Jan 2020 07:21:25 - INFO - TRIZMA DB import
Wed, 08 Jan 2020 07:21:25 - INFO - Failed on TRIZMA DB import at: 2020-01-08_07-04-04, for following calling party: 4971167271600, for agent id: trz_sstankovic, with error:(pyodbc.DataError) ('22001', '[22001] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]String or binary data would be truncated. (8152) (SQLExecDirectW)')
[SQL: insert into records values('CC2Servicenummer','Belgrad','Nicht übermittelt','trz_sstankovic',                                  '4971167271600','','Nicht übermittelt','4971167271600_Tuesday, December 31, 2019_8:01:58 AM')]
(Background on this error at: http://sqlalche.me/e/9h9h)
Wed, 08 Jan 2020 07:21:25 - INFO - 123TV DB import
Wed, 08 Jan 2020 07:21:30 - INFO - Failed on 123TV DB import at: 2020-01-08_07-04-04, for following calling party: 4971167271600, for agent id: 3046, with error:Invalid XML content received (Start tag expected, '<' not found, line 1, column 1)
Wed, 08 Jan 2020 07:24:21 - INFO - Connect to DB
Wed, 08 Jan 2020 07:24:21 - INFO - TRIZMA DB import
Wed, 08 Jan 2020 07:24:21 - INFO - 123TV DB import
Wed, 08 Jan 2020 07:24:26 - INFO - Failed on 123TV DB import at: 2020-01-08_07-04-04, for following calling party: 4953618917751, for agent id: 3067, with error:Invalid XML content received (Start tag expected, '<' not found, line 1, column 1)
Wed, 08 Jan 2020 07:24:59 - INFO - Connect to DB
Wed, 08 Jan 2020 07:24:59 - INFO - TRIZMA DB import
Wed, 08 Jan 2020 07:24:59 - INFO - 123TV DB import
Wed, 08 Jan 2020 07:25:05 - INFO - Failed on 123TV DB import at: 2020-01-08_07-04-04, for following calling party: 4964077790, for agent id: 3067, with error:Invalid XML content received (Start tag expected, '<' not found, line 1, column 1)
Wed, 08 Jan 2020 07:25:05 - INFO - Connect to DB
Wed, 08 Jan 2020 07:25:05 - INFO - TRIZMA DB import
Wed, 08 Jan 2020 07:25:05 - INFO - 123TV DB import
Wed, 08 Jan 2020 07:25:10 - INFO - Failed on 123TV DB import at: 2020-01-08_07-04-04, for following calling party: 494024180723, for agent id: 3067, with error:Invalid XML content received (Start tag expected, '<' not found, line 1, column 1)
Wed, 08 Jan 2020 07:25:42 - INFO - Connect to DB
Wed, 08 Jan 2020 07:25:42 - ERROR - Exception on /records [GET]
Traceback (most recent call last):
  File "/home/python_project/hello.py", line 80, in get
    int(agent),
ValueError: invalid literal for int() with base 10: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/python_project/hello.py", line 90, in get
    + str(e))
UnboundLocalError: local variable 'agentUsername' referenced before assignment
Wed, 08 Jan 2020 07:26:24 - INFO - Connect to DB
Wed, 08 Jan 2020 07:26:24 - INFO - TRIZMA DB import
Wed, 08 Jan 2020 07:26:24 - INFO - 123TV DB import
Wed, 08 Jan 2020 07:26:29 - INFO - Failed on 123TV DB import at: 2020-01-08_07-04-04, for following calling party: 493052283442, for agent id: 3067, with error:Invalid XML content received (Start tag expected, '<' not found, line 1, column 1)
Wed, 08 Jan 2020 07:26:29 - INFO - Connect to DB
Wed, 08 Jan 2020 07:26:29 - INFO - TRIZMA DB import
Wed, 08 Jan 2020 07:26:29 - INFO - 123TV DB import
Wed, 08 Jan 2020 07:26:34 - INFO - Failed on 123TV DB import at: 2020-01-08_07-04-04, for following calling party: 49221602602, for agent id: 3067, with error:Invalid XML content received (Start tag expected, '<' not found, line 1, column 1)
Wed, 08 Jan 2020 07:27:23 - INFO - Connect to DB
Wed, 08 Jan 2020 07:27:23 - INFO - TRIZMA DB import
Wed, 08 Jan 2020 07:27:23 - INFO - Failed on TRIZMA DB import at: 2020-01-08_07-04-04, for following calling party: 4923829617753, for agent id: trz_madamovic, with error:(pyodbc.DataError) ('22001', '[22001] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]String or binary data would be truncated. (8152) (SQLExecDirectW)')
[SQL: insert into records values('CC2Servicenummer','Belgrad','Nicht übermittelt','trz_madamovic',                                  '4923829617753','','Nicht übermittelt','4923829617753_Monday, December 30, 2019_11:13:34 AM')]
(Background on this error at: http://sqlalche.me/e/9h9h)
Wed, 08 Jan 2020 07:27:23 - INFO - 123TV DB import
Wed, 08 Jan 2020 07:27:28 - INFO - Failed on 123TV DB import at: 2020-01-08_07-04-04, for following calling party: 4923829617753, for agent id: 3067, with error:Invalid XML content received (Start tag expected, '<' not found, line 1, column 1)
Wed, 08 Jan 2020 07:28:31 - INFO - Connect to DB
Wed, 08 Jan 2020 07:28:31 - INFO - TRIZMA DB import
Wed, 08 Jan 2020 07:28:31 - INFO - 123TV DB import
Wed, 08 Jan 2020 07:28:37 - INFO - Failed on 123TV DB import at: 2020-01-08_07-04-04, for following calling party: 49266120486, for agent id: 3067, with error:Invalid XML content received (Start tag expected, '<' not found, line 1, column 1)
Wed, 08 Jan 2020 07:31:50 - INFO - Connect to DB
Wed, 08 Jan 2020 07:31:51 - INFO - TRIZMA DB import
Wed, 08 Jan 2020 07:31:51 - INFO - Failed on TRIZMA DB import at: 2020-01-08_07-04-04, for following calling party: 4951413012202, for agent id: trz_sstankovic, with error:(pyodbc.DataError) ('22001', '[22001] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]String or binary data would be truncated. (8152) (SQLExecDirectW)')
[SQL: insert into records values('CC2Servicenummer','Belgrad','Nicht übermittelt','trz_sstankovic',                                  '4951413012202','','Nicht übermittelt','4951413012202_Tuesday, December 31, 2019_9:40:28 AM')]
(Background on this error at: http://sqlalche.me/e/9h9h)
Wed, 08 Jan 2020 07:31:51 - INFO - 123TV DB import
Wed, 08 Jan 2020 07:31:56 - INFO - Failed on 123TV DB import at: 2020-01-08_07-04-04, for following calling party: 4951413012202, for agent id: 3046, with error:Invalid XML content received (Start tag expected, '<' not found, line 1, column 1)
Wed, 08 Jan 2020 07:32:01 - INFO - Connect to DB
Wed, 08 Jan 2020 07:32:01 - INFO - TRIZMA DB import
Wed, 08 Jan 2020 07:32:01 - INFO - 123TV DB import
Wed, 08 Jan 2020 07:32:06 - INFO - Failed on 123TV DB import at: 2020-01-08_07-04-04, for following calling party: 493945972148, for agent id: 3046, with error:Invalid XML content received (Start tag expected, '<' not found, line 1, column 1)
Wed, 08 Jan 2020 07:33:05 - INFO - Connect to DB
Wed, 08 Jan 2020 07:33:05 - INFO - TRIZMA DB import
Wed, 08 Jan 2020 07:33:05 - INFO - Failed on TRIZMA DB import at: 2020-01-08_07-04-04, for following calling party: 4923314832925, for agent id: trz_madamovic, with error:(pyodbc.DataError) ('22001', '[22001] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]String or binary data would be truncated. (8152) (SQLExecDirectW)')
[SQL: insert into records values('CC2Servicenummer','Belgrad','Nicht übermittelt','trz_madamovic',                                  '4923314832925','','Nicht übermittelt','4923314832925_Tuesday, December 31, 2019_9:26:04 AM')]
(Background on this error at: http://sqlalche.me/e/9h9h)
Wed, 08 Jan 2020 07:33:05 - INFO - 123TV DB import
Wed, 08 Jan 2020 07:33:10 - INFO - Failed on 123TV DB import at: 2020-01-08_07-04-04, for following calling party: 4923314832925, for agent id: 3067, with error:Invalid XML content received (Start tag expected, '<' not found, line 1, column 1)
Wed, 08 Jan 2020 07:33:37 - INFO - Connect to DB
Wed, 08 Jan 2020 07:33:38 - INFO - TRIZMA DB import
Wed, 08 Jan 2020 07:33:38 - INFO - Failed on TRIZMA DB import at: 2020-01-08_07-04-04, for following calling party: 493607180753, for agent id: trz_madamovic, with error:(pyodbc.DataError) ('22001', '[22001] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]String or binary data would be truncated. (8152) (SQLExecDirectW)')
[SQL: insert into records values('CC2Servicenummer','Belgrad','Nicht übermittelt','trz_madamovic',                                  '493607180753','','Nicht übermittelt','493607180753_Tuesday, December 31, 2019_10:47:16 AM')]
(Background on this error at: http://sqlalche.me/e/9h9h)
Wed, 08 Jan 2020 07:33:38 - INFO - 123TV DB import
Wed, 08 Jan 2020 07:33:43 - INFO - Failed on 123TV DB import at: 2020-01-08_07-04-04, for following calling party: 493607180753, for agent id: 3067, with error:Invalid XML content received (Start tag expected, '<' not found, line 1, column 1)
Wed, 08 Jan 2020 07:34:03 - INFO - Connect to DB
Wed, 08 Jan 2020 07:34:03 - INFO - TRIZMA DB import
Wed, 08 Jan 2020 07:34:03 - INFO - Failed on TRIZMA DB import at: 2020-01-08_07-04-04, for following calling party: 4944629862533, for agent id: trz_madamovic, with error:(pyodbc.DataError) ('22001', '[22001] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]String or binary data would be truncated. (8152) (SQLExecDirectW)')
[SQL: insert into records values('CC2Servicenummer','Belgrad','Nicht übermittelt','trz_madamovic',                                  '4944629862533','','Nicht übermittelt','4944629862533_Tuesday, December 31, 2019_11:14:19 AM')]
(Background on this error at: http://sqlalche.me/e/9h9h)
Wed, 08 Jan 2020 07:34:03 - INFO - 123TV DB import
Wed, 08 Jan 2020 07:34:08 - INFO - Failed on 123TV DB import at: 2020-01-08_07-04-04, for following calling party: 4944629862533, for agent id: 3067, with error:Invalid XML content received (Start tag expected, '<' not found, line 1, column 1)
Wed, 08 Jan 2020 07:34:23 - INFO - Connect to DB
Wed, 08 Jan 2020 07:34:23 - INFO - TRIZMA DB import
Wed, 08 Jan 2020 07:34:23 - INFO - Failed on TRIZMA DB import at: 2020-01-08_07-04-04, for following calling party: 4921529949498, for agent id: trz_madamovic, with error:(pyodbc.DataError) ('22001', '[22001] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]String or binary data would be truncated. (8152) (SQLExecDirectW)')
[SQL: insert into records values('CC2Servicenummer','Belgrad','Nicht übermittelt','trz_madamovic',                                  '4921529949498','','Nicht übermittelt','4921529949498_Tuesday, December 31, 2019_11:59:49 AM')]
(Background on this error at: http://sqlalche.me/e/9h9h)
Wed, 08 Jan 2020 07:34:23 - INFO - 123TV DB import
Wed, 08 Jan 2020 07:34:28 - INFO - Failed on 123TV DB import at: 2020-01-08_07-04-04, for following calling party: 4921529949498, for agent id: 3067, with error:Invalid XML content received (Start tag expected, '<' not found, line 1, column 1)
Wed, 08 Jan 2020 07:35:56 - INFO - Connect to DB
Wed, 08 Jan 2020 07:35:56 - ERROR - Exception on /records [GET]
Traceback (most recent call last):
  File "/home/python_project/hello.py", line 80, in get
    int(agent),
ValueError: invalid literal for int() with base 10: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/python_project/hello.py", line 90, in get
    + str(e))
UnboundLocalError: local variable 'agentUsername' referenced before assignment
