Wed, 08 Jan 2020 12:54:32 - INFO - Connect to DB
Wed, 08 Jan 2020 12:54:32 - INFO - TRIZMA DB import
Wed, 08 Jan 2020 12:54:32 - INFO - Failed on TRIZMA DB import at: 2020-01-08_12-49-01, for following calling party: 496781667547, for agent id: trz_madamovic, with error:(pyodbc.DataError) ('22001', '[22001] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]String or binary data would be truncated. (8152) (SQLExecDirectW)')
[SQL: insert into records values('CC2Servicenummer','Belgrad','Nicht übermittelt','trz_madamovic',                                  '496781667547','','Nicht übermittelt','496781667547_Wednesday, January 08, 2020_1:54:23 PM')]
(Background on this error at: http://sqlalche.me/e/9h9h)
Wed, 08 Jan 2020 12:54:32 - INFO - 123TV DB import
Wed, 08 Jan 2020 12:54:37 - INFO - Failed on 123TV DB import at: 2020-01-08_12-49-01, for following calling party: 496781667547, for agent id: 3067, with error:HTTPConnectionPool(host='ivr-datenimport-123tv.time4quality.de', port=80): Max retries exceeded with url: /wsdl.php?WSDL (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd4b30f66a0>: Failed to establish a new connection: [Errno 111] Connection refused',))
Wed, 08 Jan 2020 13:00:47 - INFO - Connect to DB
Wed, 08 Jan 2020 13:00:47 - INFO - TRIZMA DB import
Wed, 08 Jan 2020 13:00:47 - INFO - 123TV DB import
Wed, 08 Jan 2020 13:00:52 - INFO - Failed on 123TV DB import at: 2020-01-08_12-49-01, for following calling party: 491774337425, for agent id: 3036, with error:HTTPConnectionPool(host='ivr-datenimport-123tv.time4quality.de', port=80): Max retries exceeded with url: /wsdl.php?WSDL (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd4b3113e80>: Failed to establish a new connection: [Errno 111] Connection refused',))
