Fri, 27 Dec 2019 11:02:12 - INFO - Connect to DB
Fri, 27 Dec 2019 11:02:12 - INFO - TRIZMA DB import
Fri, 27 Dec 2019 11:02:12 - INFO - 123TV DB import
Fri, 27 Dec 2019 11:07:51 - INFO - Connect to DB
Fri, 27 Dec 2019 11:07:51 - INFO - TRIZMA DB import
Fri, 27 Dec 2019 11:07:51 - INFO - 123TV DB import
Fri, 27 Dec 2019 11:18:57 - INFO - Connect to DB
Fri, 27 Dec 2019 11:18:57 - INFO - TRIZMA DB import
Fri, 27 Dec 2019 11:18:57 - INFO - 123TV DB import
Fri, 27 Dec 2019 11:28:23 - INFO - Connect to DB
Fri, 27 Dec 2019 11:28:23 - INFO - TRIZMA DB import
Fri, 27 Dec 2019 11:28:23 - INFO - Failed on TRIZMA DB import at: 2019-12-27_10-38-22, for following calling party: 493420678460, for agent id: trz_sstankovic, with error:(pyodbc.DataError) ('22001', '[22001] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]String or binary data would be truncated. (8152) (SQLExecDirectW)')
[SQL: insert into records values('CC2Servicenummer','Belgrad','Nicht übermittelt','trz_sstankovic',                                  '493420678460','','Nicht übermittelt','493420678460_Thursday, November 28, 2019_5:53:39 PM')]
(Background on this error at: http://sqlalche.me/e/9h9h)
Fri, 27 Dec 2019 11:28:23 - INFO - 123TV DB import
Fri, 27 Dec 2019 11:29:57 - INFO - Connect to DB
Fri, 27 Dec 2019 11:29:57 - INFO - TRIZMA DB import
Fri, 27 Dec 2019 11:29:57 - INFO - Failed on TRIZMA DB import at: 2019-12-27_10-38-22, for following calling party: 496131685045, for agent id: trz_sstankovic, with error:(pyodbc.DataError) ('22001', '[22001] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]String or binary data would be truncated. (8152) (SQLExecDirectW)')
[SQL: insert into records values('CC2Servicenummer','Belgrad','Nicht übermittelt','trz_sstankovic',                                  '496131685045','','Nicht übermittelt','496131685045_Wednesday, December 11, 2019_6:53:36 PM')]
(Background on this error at: http://sqlalche.me/e/9h9h)
Fri, 27 Dec 2019 11:29:57 - INFO - 123TV DB import
Fri, 27 Dec 2019 11:30:29 - INFO - Connect to DB
Fri, 27 Dec 2019 11:30:29 - INFO - TRIZMA DB import
Fri, 27 Dec 2019 11:30:29 - INFO - Failed on TRIZMA DB import at: 2019-12-27_10-38-22, for following calling party: 4928319102206, for agent id: trz_sstankovic, with error:(pyodbc.DataError) ('22001', '[22001] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]String or binary data would be truncated. (8152) (SQLExecDirectW)')
[SQL: insert into records values('CC2Servicenummer','Belgrad','Nicht übermittelt','trz_sstankovic',                                  '4928319102206','','Nicht übermittelt','4928319102206_Wednesday, December 11, 2019_7:07:53 PM')]
(Background on this error at: http://sqlalche.me/e/9h9h)
Fri, 27 Dec 2019 11:30:29 - INFO - 123TV DB import
Fri, 27 Dec 2019 11:31:16 - INFO - Connect to DB
Fri, 27 Dec 2019 11:31:16 - ERROR - Exception on /records [GET]
Traceback (most recent call last):
  File "/home/python_project/hello.py", line 81, in get
    1)).fetchone()[0]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/python_project/hello.py", line 90, in get
    + str(e))
UnboundLocalError: local variable 'agentUsername' referenced before assignment
Fri, 27 Dec 2019 11:33:02 - INFO - Connect to DB
Fri, 27 Dec 2019 11:33:02 - INFO - TRIZMA DB import
Fri, 27 Dec 2019 11:33:02 - INFO - 123TV DB import
Fri, 27 Dec 2019 11:33:25 - INFO - Connect to DB
Fri, 27 Dec 2019 11:33:25 - INFO - TRIZMA DB import
Fri, 27 Dec 2019 11:33:25 - INFO - Failed on TRIZMA DB import at: 2019-12-27_10-38-22, for following calling party: 493496550256, for agent id: trz_sstankovic, with error:(pyodbc.DataError) ('22001', '[22001] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]String or binary data would be truncated. (8152) (SQLExecDirectW)')
[SQL: insert into records values('CC2Servicenummer','Belgrad','Nicht übermittelt','trz_sstankovic',                                  '493496550256','','Nicht übermittelt','493496550256_Thursday, December 19, 2019_10:50:40 AM')]
(Background on this error at: http://sqlalche.me/e/9h9h)
Fri, 27 Dec 2019 11:33:25 - INFO - 123TV DB import
Fri, 27 Dec 2019 11:33:40 - INFO - Connect to DB
Fri, 27 Dec 2019 11:33:40 - INFO - TRIZMA DB import
Fri, 27 Dec 2019 11:33:40 - INFO - Failed on TRIZMA DB import at: 2019-12-27_10-38-22, for following calling party: 4915112488545, for agent id: trz_sstankovic, with error:(pyodbc.DataError) ('22001', '[22001] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]String or binary data would be truncated. (8152) (SQLExecDirectW)')
[SQL: insert into records values('CC2Servicenummer','Belgrad','Nicht übermittelt','trz_sstankovic',                                  '4915112488545','','Nicht übermittelt','4915112488545_Thursday, December 19, 2019_10:59:50 AM')]
(Background on this error at: http://sqlalche.me/e/9h9h)
Fri, 27 Dec 2019 11:33:40 - INFO - 123TV DB import
Fri, 27 Dec 2019 11:40:10 - INFO - Connect to DB
Fri, 27 Dec 2019 11:40:11 - INFO - TRIZMA DB import
Fri, 27 Dec 2019 11:40:11 - INFO - Failed on TRIZMA DB import at: 2019-12-27_10-38-22, for following calling party: 49220582674, for agent id: trz_sstankovic, with error:(pyodbc.DataError) ('22001', '[22001] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]String or binary data would be truncated. (8152) (SQLExecDirectW)')
[SQL: insert into records values('CC2Servicenummer','Belgrad','Nicht übermittelt','trz_sstankovic',                                  '49220582674','','Nicht übermittelt','49220582674_Thursday, December 19, 2019_11:04:59 AM')]
(Background on this error at: http://sqlalche.me/e/9h9h)
Fri, 27 Dec 2019 11:40:11 - INFO - 123TV DB import
Fri, 27 Dec 2019 11:41:15 - INFO - Connect to DB
Fri, 27 Dec 2019 11:41:15 - INFO - TRIZMA DB import
Fri, 27 Dec 2019 11:41:15 - INFO - 123TV DB import
