Sun, 29 Dec 2019 18:52:25 - INFO - Connect to DB
Sun, 29 Dec 2019 18:52:26 - INFO - TRIZMA DB import
Sun, 29 Dec 2019 18:52:26 - INFO - 123TV DB import
Mon, 30 Dec 2019 07:03:49 - INFO - Connect to DB
Mon, 30 Dec 2019 07:03:49 - INFO - TRIZMA DB import
Mon, 30 Dec 2019 07:03:49 - INFO - 123TV DB import
Mon, 30 Dec 2019 07:07:47 - INFO - Connect to DB
Mon, 30 Dec 2019 07:07:47 - INFO - TRIZMA DB import
Mon, 30 Dec 2019 07:07:47 - INFO - 123TV DB import
Mon, 30 Dec 2019 07:09:18 - INFO - Connect to DB
Mon, 30 Dec 2019 07:09:18 - INFO - TRIZMA DB import
Mon, 30 Dec 2019 07:09:18 - INFO - 123TV DB import
Mon, 30 Dec 2019 07:09:44 - INFO - Connect to DB
Mon, 30 Dec 2019 07:09:44 - INFO - TRIZMA DB import
Mon, 30 Dec 2019 07:09:44 - INFO - 123TV DB import
Mon, 30 Dec 2019 07:10:15 - INFO - Connect to DB
Mon, 30 Dec 2019 07:10:15 - INFO - TRIZMA DB import
Mon, 30 Dec 2019 07:10:15 - INFO - 123TV DB import
Mon, 30 Dec 2019 07:10:40 - INFO - Connect to DB
Mon, 30 Dec 2019 07:10:40 - INFO - TRIZMA DB import
Mon, 30 Dec 2019 07:10:40 - INFO - 123TV DB import
Mon, 30 Dec 2019 07:20:13 - INFO - Connect to DB
Mon, 30 Dec 2019 07:20:13 - INFO - TRIZMA DB import
Mon, 30 Dec 2019 07:20:13 - INFO - Failed on TRIZMA DB import at: 2019-12-29_18-46-12, for following calling party: 491789055089, for agent id: trz_sstankovic, with error:(pyodbc.DataError) ('22001', '[22001] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]String or binary data would be truncated. (8152) (SQLExecDirectW)')
[SQL: insert into records values('CC2Servicenummer','Belgrad','Nicht übermittelt','trz_sstankovic',                                  '491789055089','','Nicht übermittelt','491789055089_Wednesday, December 11, 2019_6:34:45 PM')]
(Background on this error at: http://sqlalche.me/e/9h9h)
Mon, 30 Dec 2019 07:20:13 - INFO - 123TV DB import
Mon, 30 Dec 2019 07:22:57 - INFO - Connect to DB
Mon, 30 Dec 2019 07:22:57 - INFO - TRIZMA DB import
Mon, 30 Dec 2019 07:22:57 - INFO - 123TV DB import
